#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, set SHELL to a compliant shell.
#
#   (2) You need the command "locale" to be available.
#
#   Notes for maintainers:
#
#   (1) This script is generated from the template file gradle.wrapper.properties
#       located in gradle core distribution.
#
#   (2) Be careful with changing the shebang because on platforms like AIX it can
#       have impact on how the process is reported in process lists and how signal
#       handling works.
#
#   (3) Check also the "cygwin_encoding_handling" section below. Changes there
#       might need to be applied here as well.
#
#   (4) Keep in mind that this script gets sourced by other scripts and these
#       variables are set for these scripts as well:
#
#       - GRADLE_OPTS
#       - JAVA_OPTS
#       - JAVA_HOME
#
#       It means that these variables set by this script will affect all child
#       processes spawned by these other scripts. It is especially important
#       for JAVA_OPTS and GRADLE_OPTS variables that are used to pass arguments
#       to the JVM.
#
##############################################################################

# Attempt to set APP_HOME

# Preserve the original directory.
if [ -n "$1" ] && [ "$#" = 1 ] && [ -f "$1" ]; then
  ORIGINAL_DIR="$(dirname "$1")"
else
  ORIGINAL_DIR="${PWD}"
fi

# The name of the running program. This is used to help find the APP_HOME.
APP_BASE_NAME="${0##*/}"
# The base name of the Gradle installation.
# The installation directory can be identified by the following:
#   1. The directory pointed to by APP_HOME if it is set and valid
#   2. The directory pointed to by GRADLE_HOME if it is set and valid
#   3. The directory that contains this script (if it is a regular file)
# If the installation directory can be identified in multiple ways,
# the priority is given in the order listed above.
if [ -n "$APP_HOME" ]; then
  # Use the value of APP_HOME if it is set and valid.
  APP_HOME=$(cd "${APP_HOME:-.}" && pwd -P) || exit
else
  # Find the directory of the Gradle wrapper.
  WRAPPER_DIR=$(dirname "$(readlink -f "$0")")
  # Set the installation directory to the parent directory of the wrapper.
  APP_HOME="${WRAPPER_DIR}/.."
  # Reset the value of APP_HOME if it is not a directory.
  if [ ! -d "${APP_HOME}" ]; then
    # If the installation directory is not found, use the directory of the wrapper.
    APP_HOME="${WRAPPER_DIR}"
  fi
fi

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in                #(
  CYGWIN* )           cygwin=true  ;; #(
  Darwin* )           darwin=true  ;; #(
  MSYS* | MINGW* )    msys=true    ;; #(
  NONSTOP* )          nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined; we use -n instead.
        # It is likely that we must set the value here quickly to avoid
        # running out of file descriptors in the ulimit command itself.
        # After having removed the limit, we no longer need to worry about it.
        # shellcheck disable=SC2039
        MAX_FD=$(ulimit -H -n) ||
           warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -S is undefined; we use -n instead.
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit: $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * supplied properties
#   * -Dgradle.home
#   * -d64
#   * -classpath
#   * standalone file
#   * jvm arguments

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                           # don't fix window options               #(
              /?*)  t=${arg#/} t=/${t%%/*}            # looks like a POSIX filepath              #(
                    [ -e "$t" ] ;;                    #(
              *)    false ;;
            esac
        then
            # arg is not option, so it could be a path.
            # However, it might also be an argument starting with slash.
            # Check if arg itself exists as a file or directory.
            # If it does, then it is a path and needs to be converted.
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        # Roll the args list around exactly as many times as the number of
        # args, prepending the last value to the next iteration of the args list
        # until we get down to the first arg.
        # shellcheck disable=SC2034
        RECYCLED="" ; for val in "$@" 'ArGuMeNt' ; do
            if [ "$val" = 'ArGuMeNt' ] ; then
                # Do not switch the first argument over - it will be the JAVACMD
                RECYCLED="$arg $RECYCLED"
            else
                RECYCLED="$val $RECYCLED"
            fi
        done
        # Set the new positional parameters based on the recycled arguments
        set -- $RECYCLED
    done
fi

# Collect all arguments for the JVM:
# Add the main program jar to the JVM options
exec "$JAVACMD" -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"